# Generated by Django 5.2.13 on 2026-04-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_id', models.CharField(help_text='e.g., @I1@', max_length=20, unique=True)),
                ('given_name', models.CharField(blank=True, max_length=150)),
                ('surname', models.CharField(blank=True, max_length=150)),
                ('name_prefix', models.CharField(blank=True, help_text='e.g., Dr., Sir', max_length=50)),
                ('name_suffix', models.CharField(blank=True, help_text='e.g., Jr., III', max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_id', models.CharField(blank=True, help_text='e.g., @S1@', max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publication_facts', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_id', models.CharField(help_text='e.g., @F1@', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_husband', to='genview.individual')),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_wife', to='genview.individual')),
                ('sources', models.ManyToManyField(blank=True, related_name='families', to='genview.source')),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.AddField(
            model_name='individual',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='genview.source'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BIRT', 'Birth'), ('CHR', 'Christening'), ('DEAT', 'Death'), ('BURI', 'Burial'), ('RELI', 'Religion'), ('OCCU', 'Occupation'), ('MARR', 'Marriage'), ('DIV', 'Divorce'), ('ENGA', 'Engagement')], max_length=10)),
                ('raw_date', models.CharField(blank=True, help_text="Raw GEDCOM date string e.g. 'ABT 1900'", max_length=100)),
                ('parsed_date', models.DateField(blank=True, help_text='Parsed date for sorting/filtering', null=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genview.family')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genview.individual')),
                ('sources', models.ManyToManyField(blank=True, related_name='events', to='genview.source')),
            ],
        ),
        migrations.CreateModel(
            name='ChildFamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('B', 'Biological'), ('A', 'Adopted'), ('F', 'Foster'), ('S', 'Step'), ('U', 'Unknown')], default='B', max_length=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genview.family')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parental_families', to='genview.individual')),
            ],
            options={
                'unique_together': {('child', 'family')},
            },
        ),
    ]
