# Generated by Django 5.2.13 on 2026-06-02 19:49

import django.db.models.deletion
import genview.models
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="GEDCOM Tag"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Anzeigename")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IND", "Personen-Ereignis"),
                            ("FAM", "Familien-Ereignis"),
                            ("BOTH", "Beides"),
                        ],
                        default="IND",
                        max_length=4,
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ereignis-Typ",
                "verbose_name_plural": "Ereignis-Typen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Individual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gedcom_id",
                    models.CharField(
                        blank=True,
                        help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                        max_length=20,
                        null=True,
                        verbose_name="GEDCOM ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("given_name", models.CharField(blank=True, max_length=150)),
                ("surname", models.CharField(blank=True, max_length=150)),
                (
                    "name_prefix",
                    models.CharField(
                        blank=True, help_text="z.\u202fB. Dr., Sir", max_length=50
                    ),
                ),
                (
                    "name_suffix",
                    models.CharField(
                        blank=True, help_text="z.\u202fB. Jr., III", max_length=50
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["surname", "given_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gedcom_id",
                    models.CharField(
                        blank=True,
                        help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                        max_length=20,
                        null=True,
                        verbose_name="GEDCOM ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Ortsname")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Breitengrad (Latitude)",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Längengrad (Longitude)",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gedcom_id",
                    models.CharField(
                        blank=True,
                        help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                        max_length=20,
                        null=True,
                        verbose_name="GEDCOM ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Titel / Kurzbeschreibung", max_length=255
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255)),
                ("publication_facts", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gedcom_id",
                    models.CharField(
                        blank=True,
                        help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                        max_length=20,
                        null=True,
                        verbose_name="GEDCOM ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_families",
                        to="genview.family",
                    ),
                ),
                (
                    "husband",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="families_as_husband",
                        to="genview.individual",
                    ),
                ),
                (
                    "wife",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="families_as_wife",
                        to="genview.individual",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="families", to="genview.source"
                    ),
                ),
                (
                    "gedcom_tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="families",
                        to="genview.tree",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Families",
                "ordering": ["gedcom_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_date",
                    models.CharField(
                        blank=True,
                        help_text="Original GEDCOM‑Datum‑String, z.\u202fB. 'ABT 1900'",
                        max_length=100,
                    ),
                ),
                (
                    "parsed_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Geparstes Datum (für Sortierung/Filter)",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="genview.eventtype",
                        verbose_name="Ereignistyp",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="genview.family",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="genview.individual",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="genview.place",
                        verbose_name="Ort",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="genview.source",
                        verbose_name="Quellen",
                    ),
                ),
                (
                    "gedcom_tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="genview.tree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ereignis",
                "verbose_name_plural": "Ereignisse",
            },
        ),
        migrations.CreateModel(
            name="AlternativeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Vorname"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nachname"
                    ),
                ),
                (
                    "name_type",
                    models.CharField(
                        choices=[
                            ("married", "Ehename"),
                            ("maiden", "Geburtsname (abweichend)"),
                            ("aka", "Alias / Spitzname"),
                            ("immigrant", "Einwanderer-Name"),
                            ("unknown", "Alternativer Name"),
                        ],
                        default="married",
                        max_length=20,
                        verbose_name="Namens-Typ",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_names",
                        to="genview.individual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativer Name",
                "verbose_name_plural": "Alternative Namen",
            },
        ),
        migrations.AddField(
            model_name="individual",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="individuals", to="genview.source"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="gedcom_tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="genview.tree",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="gedcom_tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="genview.tree",
            ),
        ),
        migrations.CreateModel(
            name="MediaObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gedcom_id",
                    models.CharField(
                        blank=True,
                        help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                        max_length=20,
                        null=True,
                        verbose_name="GEDCOM ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=genview.models.tree_media_directory_path,
                        verbose_name="Datei/Bild",
                    ),
                ),
                (
                    "gedcom_original_filepath",
                    models.CharField(
                        blank=True,
                        help_text="Temporärer Speicher für den Dateipfad aus der GEDCOM-Datei.",
                        max_length=500,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Foto / Portrait"),
                            ("DOCUMENT", "Dokument / Urkunde"),
                        ],
                        default="PHOTO",
                        max_length=10,
                        verbose_name="Kategorie",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "is_portrait",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Dieses Bild wird als Portrait auf der Personen‑Detail‑Seite angezeigt.",
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ereignisse, mit denen dieses Medium verknüpft ist",
                        related_name="media_objects",
                        to="genview.event",
                    ),
                ),
                (
                    "families",
                    models.ManyToManyField(
                        blank=True, related_name="media_objects", to="genview.family"
                    ),
                ),
                (
                    "individuals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="media_objects",
                        to="genview.individual",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="media_objects", to="genview.source"
                    ),
                ),
                (
                    "gedcom_tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediaobjects",
                        to="genview.tree",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_portrait", "title"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="individual",
            name="gedcom_tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individuals",
                to="genview.tree",
            ),
        ),
        migrations.CreateModel(
            name="TreeMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("VIEWER", "Can only view data"),
                            ("EDITOR", "Can edit individuals and families"),
                            (
                                "ADMIN",
                                "Can edit data, import GEDCOMs, and invite users",
                            ),
                        ],
                        default="VIEWER",
                        max_length=10,
                    ),
                ),
                (
                    "gedcom_tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="genview.tree",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildFamilyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("B", "Biological"),
                            ("A", "Adopted"),
                            ("F", "Foster"),
                            ("S", "Step"),
                            ("U", "Unknown"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="genview.family",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parental_families",
                        to="genview.individual",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["child", "family"],
                        name="genview_chi_child_i_00c802_idx",
                    )
                ],
                "unique_together": {("child", "family")},
            },
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["title"], name="genview_sou_title_0b06cb_idx"),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_source_unique_gedcom_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_place_unique_gedcom_id",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("gedcom_tree", "name")},
        ),
        migrations.AddConstraint(
            model_name="mediaobject",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_mediaobject_unique_gedcom_id",
            ),
        ),
        migrations.AddIndex(
            model_name="individual",
            index=models.Index(
                fields=["surname", "given_name"], name="genview_ind_surname_e30eda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="individual",
            index=models.Index(fields=["sex"], name="genview_ind_sex_eaac70_idx"),
        ),
        migrations.AddConstraint(
            model_name="individual",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_individual_unique_gedcom_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="family",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_family_unique_gedcom_id",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["individual", "event_type", "parsed_date"],
                name="genview_eve_individ_d176a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["family", "event_type", "parsed_date"],
                name="genview_eve_family__6d816f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="treemembership",
            unique_together={("user", "gedcom_tree")},
        ),
    ]
