# Generated by Django 5.2.13 on 2026-05-14 08:32

import genview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaobject',
            name='file',
            field=models.FileField(upload_to=genview.models.tree_media_directory_path, verbose_name='Datei/Bild'),
        ),
    ]
