# Generated by Django 5.2.13 on 2026-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['surname', 'given_name']},
        ),
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_id', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='gedcom_media/')),
                ('description', models.TextField(blank=True)),
                ('families', models.ManyToManyField(blank=True, related_name='media_objects', to='genview.family')),
                ('individuals', models.ManyToManyField(blank=True, related_name='media_objects', to='genview.individual')),
                ('sources', models.ManyToManyField(blank=True, related_name='media_objects', to='genview.source')),
            ],
        ),
    ]
