# Generated by Django 5.2.13 on 2026-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaobject",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ereignisse, mit denen dieses Medium verknüpft ist",
                related_name="media_objects",
                to="genview.event",
            ),
        ),
    ]
