# Generated by Django 5.2.13 on 2026-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Ereignis", "verbose_name_plural": "Ereignisse"},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="genview_eve_event_t_45a2bf_idx",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["individual", "event_type", "parsed_date"],
                name="genview_eve_individ_d176a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["family", "event_type", "parsed_date"],
                name="genview_eve_family__6d816f_idx",
            ),
        ),
    ]
