# Generated by Django 5.2.13 on 2026-06-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0002_alter_event_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternativeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Vorname"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nachname"
                    ),
                ),
                (
                    "name_type",
                    models.CharField(
                        choices=[
                            ("married", "Ehename"),
                            ("maiden", "Geburtsname (abweichend)"),
                            ("aka", "Alias / Spitzname"),
                            ("immigrant", "Einwanderer-Name"),
                            ("unknown", "Alternativer Name"),
                        ],
                        default="married",
                        max_length=20,
                        verbose_name="Namens-Typ",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_names",
                        to="genview.individual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativer Name",
                "verbose_name_plural": "Alternative Namen",
            },
        ),
    ]
