# Generated by Django 5.2.13 on 2026-05-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0002_mediaobject_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaobject",
            name="category",
            field=models.CharField(
                choices=[
                    ("PHOTO", "Foto / Portrait"),
                    ("DOCUMENT", "Dokument / Urkunde"),
                ],
                default="PHOTO",
                max_length=10,
                verbose_name="Kategorie",
            ),
        ),
    ]
