# Generated by Django 5.2.13 on 2026-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0003_mediaobject_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
