# Generated by Django 5.2.13 on 2026-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0005_alter_family_gedcom_id_alter_individual_gedcom_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="family",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="individual",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="family",
            name="gedcom_id",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                max_length=20,
                null=True,
                verbose_name="GEDCOM ID",
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="gedcom_id",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                max_length=20,
                null=True,
                verbose_name="GEDCOM ID",
            ),
        ),
        migrations.AlterField(
            model_name="mediaobject",
            name="gedcom_id",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                max_length=20,
                null=True,
                verbose_name="GEDCOM ID",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="gedcom_id",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                max_length=20,
                null=True,
                verbose_name="GEDCOM ID",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="gedcom_id",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM Referenz, z.B. @I1@, @F2@ …",
                max_length=20,
                null=True,
                verbose_name="GEDCOM ID",
            ),
        ),
    ]
