# Generated by Django 5.2.13 on 2026-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0006_alter_family_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="family",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_family_unique_gedcom_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="individual",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_individual_unique_gedcom_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaobject",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_mediaobject_unique_gedcom_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_place_unique_gedcom_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("gedcom_tree", "gedcom_id"),
                name="genview_source_unique_gedcom_id",
            ),
        ),
    ]
