# Generated by Django 5.2.13 on 2026-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0007_family_genview_family_unique_gedcom_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaobject",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
