networks:
  backend_net:
    name: genview_network

volumes:
  models_data:
    name: shared_ml_models
  genview_data:
    name: static_pictures_data
  ollama_data:
    name: ollama_data

services:
  rootnode:
    image: localhost/rootnode:latest
    container_name: rootnode
    restart: unless-stopped
    ports:
      - 8010:8003
    volumes:
      - genview_data:/data/genview:z
    networks:
      - backend_net
    env_file:
      - .env
