# Generated by Django 6.0.6 on 2026-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_tree_query",
                    models.BooleanField(
                        default=True,
                        help_text="Natürliche Sprache und strukturierte Abfragen am Stammbaum. Unklare Fragen können ein Sprachmodell (Ollama) aufrufen.",
                        verbose_name="Stammbaum fragen",
                    ),
                ),
                (
                    "enable_ocr",
                    models.BooleanField(
                        default=True,
                        help_text="Text aus Dokumenten extrahieren und Ereignis-Vorschläge erzeugen. Benötigt den OCR-Dienst (textnode).",
                        verbose_name="OCR / Texterkennung",
                    ),
                ),
                (
                    "enable_face_recognition",
                    models.BooleanField(
                        default=True,
                        help_text="Gesichter auf Fotos erkennen und Personen vorschlagen. Benötigt den Gesichtsdienst (facenode).",
                        verbose_name="Gesichtserkennung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anwendungseinstellungen",
                "verbose_name_plural": "Anwendungseinstellungen",
            },
        ),
    ]
