# Generated by Django 6.0.6 on 2026-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_appsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="enable_colorize",
            field=models.BooleanField(
                default=False,
                help_text="Schwarz-Weiß-Fotos automatisch kolorisieren. Benötigt den Kolorierungsdienst (colornode) und ist speicherintensiv.",
                verbose_name="Fotos kolorisieren",
            ),
        ),
    ]
