# Generated by Django 6.0.6 on 2026-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="raw_date",
            field=models.CharField(
                blank=True,
                help_text="Original GEDCOM-Datum-String, z. B. 'ABT 1900'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="name_prefix",
            field=models.CharField(
                blank=True, help_text="z. B. Dr., Sir", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="name_suffix",
            field=models.CharField(
                blank=True, help_text="z. B. Jr., III", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tree",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiviert, kann jeder den Baum sehen, ohne Membership.",
                verbose_name="Öffentlicher Stammbaum",
            ),
        ),
    ]
