# Generated by Django 6.0.6 on 2026-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0002_alter_event_raw_date_alter_individual_name_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Wenn deaktiviert, werden Ereignisse dieses Typs im Frontend (z.B. Timeline) ausgeblendet.",
                verbose_name="Sichtbar",
            ),
        ),
    ]
