# Generated by Django 6.0.4 on 2026-06-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0003_eventtype_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('tag_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_tags', to='genview.individual')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facetags', to='genview.mediaobject')),
            ],
            options={
                'unique_together': {('media', 'x', 'y', 'width', 'height')},
            },
        ),
    ]
