# Generated by Django 6.0.4 on 2026-06-20 21:11

import genview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0004_facetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to=genview.models.tree_annotated_media_directory_path),
        ),
    ]
