# Generated by Django 6.0.6 on 2026-06-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0005_mediaobject_annotated_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaobject',
            name='annotated_image',
        ),
    ]
