# Generated by Django 6.0.6 on 2026-06-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0006_remove_mediaobject_annotated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetag',
            name='confidence',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facetag',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facetag',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_faces', to='genview.individual'),
        ),
        migrations.AlterField(
            model_name='facetag',
            name='width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facetag',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facetag',
            name='y',
            field=models.FloatField(),
        ),
    ]
