# Generated by Django 6.0.6 on 2026-06-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0007_facetag_confidence_alter_facetag_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facetag',
            old_name='height',
            new_name='height_percent',
        ),
        migrations.RenameField(
            model_name='facetag',
            old_name='width',
            new_name='width_percent',
        ),
        migrations.RenameField(
            model_name='facetag',
            old_name='x',
            new_name='x_percent',
        ),
        migrations.RenameField(
            model_name='facetag',
            old_name='y',
            new_name='y_percent',
        ),
        migrations.AlterUniqueTogether(
            name='facetag',
            unique_together={('media', 'x_percent', 'y_percent', 'width_percent', 'height_percent')},
        ),
    ]
