# Generated by Django 6.0.6 on 2026-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0008_rename_height_facetag_height_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetag',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Der mathematische Gesichts-Vektor aus DeepFace.', null=True),
        ),
    ]
