# Generated by Django 6.0.4 on 2026-06-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0009_facetag_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='extracted_text',
            field=models.CharField(blank=True, null=True),
        ),
    ]
