# Generated by Django 6.0.6 on 2026-07-26 17:13

import genview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0010_mediaobject_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='thumb_mini',
            field=models.ImageField(blank=True, editable=False, help_text='Mini-Thumbnail (≈ 80\u202f×\u202f80\u202fpx)', null=True, upload_to=genview.models.tree_media_directory_path),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='thumb_small',
            field=models.ImageField(blank=True, editable=False, help_text='Small-Thumbnail (≈ 200\u202f×\u202f200\u202fpx)', null=True, upload_to=genview.models.tree_media_directory_path),
        ),
    ]
