# Generated by Django 6.0.6 on 2026-07-27 18:56

import genview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genview', '0011_mediaobject_thumb_mini_mediaobject_thumb_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaobject',
            name='thumb_mini',
            field=models.ImageField(blank=True, editable=False, help_text='Mini-Thumbnail (≈ 80 × 80 px)', null=True, upload_to=genview.models.tree_thumbs_mini_directory_path),
        ),
        migrations.AlterField(
            model_name='mediaobject',
            name='thumb_small',
            field=models.ImageField(blank=True, editable=False, help_text='Small-Thumbnail (≈ 200 × 200 px)', null=True, upload_to=genview.models.tree_thumbs_small_directory_path),
        ),
    ]
