# Generated by Django 6.0.6 on 2026-08-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0012_alter_mediaobject_thumb_mini_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="starting_individual",
            field=models.ForeignKey(
                blank=True,
                help_text="Person für Schnellzugriff und Start der interaktiven Baumansicht.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="genview.individual",
                verbose_name="Startperson",
            ),
        ),
    ]
