# Generated by Django 5.x on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genview", "0018_entity_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="gov_data",
            field=models.JSONField(
                blank=True,
                help_text="Zwischengespeicherte GOV-Objektdaten (Namen, Zeiten, Koordinaten).",
                null=True,
                verbose_name="GOV-Daten",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="gov_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Kennung im Geschichtlichen Ortsverzeichnis (z.B. NEURCHJO94KE).",
                max_length=64,
                verbose_name="GOV-Kennung",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="gov_synced_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="GOV zuletzt geladen",
            ),
        ),
    ]
