"""
Django settings for rootnode project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
from pathlib import Path

from logging import getLogger

logger = getLogger(__name__)

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')
# True while running manage.py test / pytest (relaxes some fail-closed checks).
TESTING = any(
    arg == 'test' or arg.endswith('pytest') or 'pytest' in arg
    for arg in __import__('sys').argv
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG is False")
elif not DEBUG and str(SECRET_KEY).startswith("django-insecure"):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("Insecure SECRET_KEY is not allowed when DEBUG is False")

ah_raw = os.getenv('ALLOWED_HOSTS')
if ah_raw:
    # split, strip Leerzeichen, entferne leere Einträge
    ALLOWED_HOSTS = [origin.strip() for origin in ah_raw.split(',') if origin.strip()]
else:
    ALLOWED_HOSTS = []
if not DEBUG and not ALLOWED_HOSTS:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("ALLOWED_HOSTS must be set when DEBUG is False")
logger.info("--- Allowed Hosts ---")
logger.info(ALLOWED_HOSTS)
logger.info("---------------------")

csrf_raw = os.getenv('CSRF_TRUSTED_ORIGINS')
if csrf_raw:
    # split, strip Leerzeichen, entferne leere Einträge
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_raw.split(',') if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

logger.info("--- CSRF Hosts ------")
logger.info(CSRF_TRUSTED_ORIGINS)
logger.info("---------------------")


INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Application definition

INSTALLED_APPS = [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'genview.apps.GenviewConfig',
    'django_otp',
    'django_otp.plugins.otp_totp',          # TOTP (Google-Authenticator)
    'django_otp.plugins.otp_static',        # Backup-Tokens
    'django_otp.plugins.otp_email',
    'two_factor',  
    'two_factor.plugins.email',
]


if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
]

if DEBUG:
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

# Schalte die automatische Anlage nur in den gewünschten Umgebungen an:
CREATE_SUPERUSER_ON_STARTUP = True   # z. B. in dev-settings.py

ROOT_URLCONF = 'rootnode.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # TODO: remove later
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'genview.context_processors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'rootnode.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.path.exists('/data/genview'):
    GENVIEW = Path('/data/genview')
else:
    # Safe fallback for local development outside of Docker
    GENVIEW = BASE_DIR

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': GENVIEW / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de'

LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ------------------------------------------------------------------
# Statische Dateien
# ------------------------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = GENVIEW / 'staticfiles'         # für collectstatic (Produktiv)
STATICFILES_DIRS = [BASE_DIR / 'static']      # dein lokaler Entwicklungs-Ordner

# ------------------------------------------------------------------
# WhiteNoise (empfohlen)
# ------------------------------------------------------------------
# Komprimierte (gzip/br) und versionierte Dateien benutzen:
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ------------------------------------------------------------------
# Security headers / cookies
# ------------------------------------------------------------------
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True  # obsolete in modern browsers; harmless if set

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Production-only TLS hardening (keep local HTTP working when DEBUG=True)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'two_factor:login'              # Name der 2FA-Login-View
LOGIN_REDIRECT_URL = 'genview:tree-list'   # Ziel nach erfolgreichem Login
LOGOUT_REDIRECT_URL = 'two_factor:login'

# The URL path where files will be accessible in the browser
MEDIA_URL = '/media/'

# The absolute folder path on your computer where Django will save the files
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = GENVIEW / 'media'

# Cap in-memory uploads (DoS mitigation); forms also enforce 20 MiB.
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "suppress_client_error_traceback": {
            "()": "rootnode.logging_filters.SuppressClientErrorTracebackFilter",
        },
    },
    "formatters": {
        "extended": {
            "format": "{levelname} {asctime} {name} {funcName} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "verbose": {
            "format": "{levelname} {asctime} {name} {funcName}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["suppress_client_error_traceback"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    # Override Django's DEFAULT_LOGGING handlers (which have no filter and
    # print PermissionDenied with a full stack before our root handler runs).
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}